// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPMRp2UWE_X6ruAZQYJ-Bu30a0eaIRuc',
    appId: '1:921333516034:web:815c1e1e8050623b1da41b',
    messagingSenderId: '921333516034',
    projectId: 'k7w1p59r13xmssiezw5dfjogdhfvdu',
    authDomain: 'k7w1p59r13xmssiezw5dfjogdhfvdu.firebaseapp.com',
    storageBucket: 'k7w1p59r13xmssiezw5dfjogdhfvdu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4spLooher-JZ604b-QdYnbrQ1zSsEjvA',
    appId: '1:921333516034:android:482212b5792ebf6c1da41b',
    messagingSenderId: '921333516034',
    projectId: 'k7w1p59r13xmssiezw5dfjogdhfvdu',
    storageBucket: 'k7w1p59r13xmssiezw5dfjogdhfvdu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lZ7Oyx4TAD7EvjkjIWcS4IX_wFmx9QY',
    appId: '1:921333516034:ios:451cb622ddc0cd021da41b',
    messagingSenderId: '921333516034',
    projectId: 'k7w1p59r13xmssiezw5dfjogdhfvdu',
    storageBucket: 'k7w1p59r13xmssiezw5dfjogdhfvdu.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
